### ISSUE TITLE
Error thrown from module in v12

### ISSUE THREAD

**Issue by strongpauly** [shemetz/ZoomPanOptions#58]
foundry.js:756 Error: Error thrown in hooked function '' for hook 'canvasReady'. This is not a registered game setting
    at ClientSettings.get (foundry.js:3391:42)
    at getSetting (zoom-pan-options.js:6:24)
    at updateDragResistance (zoom-pan-options.js:437:19)
    at Object.fn (zoom-pan-options.js:695:3)
    at #call (foundry.js:733:20)
    at Hooks.call (foundry.js:715:38)
    at foundry.js:23422:13
    at async Scene.view (foundry.js:20331:7)
    at async Game.initializeCanvas (foundry.js:8921:20)
    at async Game.setupGame (foundry.js:8755:5)
    at async Game._initializeGameView (foundry.js:10055:5)
    at async Game.initialize (foundry.js:8673:5)

**Comment by shemetz** [comment]
Could you try seeing if i's fixed in v1.13.1 (in a new world)?  I'm not able to eaisly update to V12 yet, so I can't confirm that my fix worked.

(thanks for the report!  sorry that my fix is different to your PR)
