### ISSUE TITLE
Module won't load in v12 Build 318

### ISSUE THREAD

**Issue by strongpauly** [shemetz/ZoomPanOptions#60]
Console shows this error:

```
foundry.js:756 LibWrapperPackageError: Error thrown in hooked function '' for hook 'setup'. Error detected in module Zoom/Pan Options. It is likely this module has not been updated for FVTT Version 12 Stable.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/shemetz/ZoomPanOptions
Report this issue here: https://github.com/shemetz/ZoomPanOptions/issues

== Technical Details:
Detected by libWrapper.
Package ID= zoom-pan-options
Error= Could not find target 'AdaptiveFXAAFilter.prototype._computeLumaReduction': Could not find root scope 'AdaptiveFXAAFilter'.

    at pe (libWrapper-api.js:135:10)
    at de (libWrapper-api.js:152:19)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at Object.fn (zoom-pan-options.js:680:14)
    at #call (foundry.js:733:20)
    at Hooks.callAll (foundry.js:690:17)
    at Game.setupGame (foundry.js:8941:11)
    at async Game._initializeGameView (foundry.js:10257:5)
onError @ foundry.js:756
```

Seems to have been caused by https://github.com/foundryvtt/foundryvtt/issues/10209

**Comment by shemetz** [comment]
Fixed in 1.14.0
